version: "3"

services:
  pywb-arquivo-framed:
    build:
      context: framed
    ports:
      - 8081:8081
  pywb-arquivo-unframed:
    build:
      context: unframed
    ports:
      - 8082:8082
  pywb-arquivo-save:
    build:
      context: save
    ports:
      - 8586:8586
    volumes:
      - ./save/collections:/app/collections
  pywb-arquivo-patching:
    build:
      context: patching
    ports:
      - 8083:8083
    volumes:
      - ./patching/collections:/app/collections
