
services:
  pywb-arquivo-framed:
    build:
      context: framed
    ports:
      - 8081:8081
    volumes:
      - ${CDX_FOLDER:-/data/indexes_cdx}:/data/indexes_cdx
    network_mode: host
  pywb-arquivo-unframed:
    build:
      context: unframed
    ports:
      - 8082:8082
    volumes:
      - ${CDX_FOLDER:-/data/indexes_cdx}:/data/indexes_cdx
    network_mode: host
  pywb-arquivo-save:
    build:
      context: save
    ports:
      - 8586:8586
    volumes:
      - ${CDX_FOLDER:-/data/indexes_cdx}:/data/indexes_cdx
      - ./save/collections:/app/collections
    network_mode: host
  pywb-arquivo-patching:
    build:
      context: patching
    ports:
      - 8083:8083
    volumes:
      - ${CDX_FOLDER:-/data/indexes_cdx}:/data/indexes_cdx
      - ./patching/collections:/app/collections
    network_mode: host
