collections:
  arquivo: 
    index_group:
      arquivo: memento+https://arquivo.pt/wayback/
    metadata:
      arquivoweb_app_url: https://preprod.arquivo.pt  # to use the preprod environment
    #  arquivoweb_app_url: http://localhost:8080  # to use the localhost development
    
head_insert_html: head_insert_mobile.html
frame_insert_html: frame_insert_mobile.html
error_html: error_mobile.html
not_found_html: not_found_mobile.html

framed_replay: true
redirect_exact: true
debug: True

