collections:
  arquivo: memento+https://arquivo.pt/wayback/
    
head_insert_html: head_insert_mobile.html
frame_insert_html: frame_insert_mobile.html
error_html: error_mobile.html
not_found_html: not_found_mobile.html

framed_replay: true
redirect_exact: true
debug: True

