collections:
    '':
        index_paths: /data/indexes_split_cdx/indexes_split_cdx

# configure path to warcs here
archive_paths:
    - http://p62.arquivo.pt:8080/arcproxy/arcproxy/
    - http://p58.arquivo.pt:8080/arcproxy/arcproxy/

enable_cdx_api: cdx
framed_replay: true
static_routes:
          static/resources: ./static_mobile/
          static/__pywb: pywb/static/

head_insert_html: head_insert_mobile.html
frame_insert_html: frame_insert_mobile.html
banner_html: banner_mobile.html
error_html: error_mobile.html
not_found_html: not_found_mobile.html

metadata:
          search_location: http://m.p27.arquivo.pt
