Content = {
    months: 
		{ 	 '01': "January",
			 '02': "February",
			 '03': "March",
			 '04': "April",
			 '05': "May",
			 '06': "June",
			 '07': "July",
			 '08': "August",
			 '09': "September",
			 '10': "October",
			 '11': "November",
			 '12': "December",
		},
    shortMonths: 
		{ 	 '01': "Jan",
			 '02': "Feb",
			 '03': "Mar",
			 '04': "Apr",
			 '05': "May",
			 '06': "Jun",
			 '07': "Jul",
			 '08': "Aug",
			 '09': "Sep",
			 '10': "Oct",
			 '11': "Nov",
			 '12': "Dec",
		},
    savedInArchive:"We archived",
    versionsStored:"Versions table",
    versionsPage:"versions of",
    between:"between",
    and:"and",
    resultsQuestion:"Did you want to see webpages with the text:",
    moreOptions:"More options",
    lessOptions:"Less options",
    help:"Help",
    helpHref:"http://sobre.arquivo.pt/help/faq?set_language=en",
    newSearch:"New search",
    at:"at",
    shareMessage:"Arquivo.pt: search pages from the past.",
    language:"en",
    otherDates:"Versions table",
    emailMessage:"Interesting Web Page from the Past &body=",
    noResultsFound:"No results were found for the query:",
    suggestions:"We suggest that you:",
    checkSpelling:"Verify the URL.",
    differentKeywords:"Try different keywords.",
    generalWords:"Try more general words.",
    internetArchive:"Search the",
    suggestSiteArchived:"the site to be archived.", 
    suggestUrl:"http://sobre.arquivo.pt/how-to-participate/suggest-a-site?suggested-site=",
    suggest:"Suggest", 
    mementoFind:"Search other web archives",
    embargo:"Embargo",
    embargoUrl:"http://sobre.arquivo.pt/help/access-to-archived-contents#section-6",
    notArchived:"Not Archived",
    otherLanguage: "PT" ,
    preservedByArquivo: " - preserved by Arquivo.pt" ,
    faceTitle: "Share On Facebook",
    twitterTitle: "Share On Twitter",
    mailTitle: "Share by Email",
    screenTitle: "Download Screenshot",
    printTitle: "Print the Page",
    changeLanguageTitle: "Mudar para Portugu&#234;s",
    versionsStoredTable:"Table of Versions",
    suggestArchive: "Suggest this website for archive",
    ups: "Ups...",
    theWebsite: "The Website",
    notArchivedYet: "wasn't archived yet.",
    searchTitle: "search in Arquivo.pt",
    otherArchives: "Search in other archives",
    table: "Table",
    completePage: "Complete the Page", 
    downloadTitle: "Download Screenshot",
    downloadPopup: "Download screenshot of this page?",    
    downloadMessage: "Download",
    downloadCancel: "Cancel",
    title500: "Ooops! An error has occured",
    subtitle500: "We are sorry for this unexpected behaviour.",
    suggestionsTitle500: "You can:",
    suggestionsFeedback500: "Warn us about this missing page",
    goHome500: "Return to the homepage",
    homePagetitle: "Go to the homepage", 
    contact: "contact?set_language=en" ,
    iongrid: "Table of versions icon" ,
    reconstructImg: "Complete the page icon"  ,
    screenshotIcon: "Download Screenshot icon",
    printIcon: "Print the page icon",
    facebookIcon: "Share on Facebook icon" ,
    twitterIcon: "Share on Twitter icon",
    emailIcon: "Share by email icon",
    minimizeMaximizeTitle: "Minimize or maximize toolbar",
    minimizeMaximizeIcon: "Minimize or maximize toolbar icon",
    allVersions: "List versions",
    facebook: "Facebook",
    twitter: "Twitter",
    email: "Email",
    otherLanguageExtended: "Portugu&#234;s",
    complete: "Complete",
    saveImage: "Screenshot",
    print: "Print",
    share: "Share",
    tools: "Tools" ,
    printModalTitle: "Print this page?",
    cancel: "Cancel",
    saveAsImage: "Take a screenshot of this page?",
    completeThisPage: "Complete this page?",
    leavingArquivo: "You are leaving Arquivo.pt",
    toBeCompleted: "This page might be completed with missing information" ,
    helpHref:"http://sobre.arquivo.pt/en/help/"   

};