Content = {
    months: 
		{ 	 '01': "Janeiro",
			 '02': "Fevereiro",
			 '03': "Mar&#231;o",
			 '04': "Abril",
			 '05': "Maio",
			 '06': "Junho",
			 '07': "Julho",
			 '08': "Agosto",
			 '09': "Setembro",
			 '10': "Outubro",
			 '11': "Novembro",
			 '12': "Dezembro",
		},
    shortMonths: 
		{ 	 '01': "Jan",
			 '02': "Fev",
			 '03': "Mar",
			 '04': "Abr",
			 '05': "Mai",
			 '06': "Jun",
			 '07': "Jul",
			 '08': "Ago",
			 '09': "Set",
			 '10': "Out",
			 '11': "Nov",
			 '12': "Dez",
		},
    savedInArchive:"Foram gravadas no arquivo",
    versionsStored:"Tabela de vers&#245;es",
    versionsPage:"vers&#245;es de",
    between:"entre",
    and:"e",
    resultsQuestion:"Pretendia ver os resultados das p&#225;ginas que cont&#234;m o texto:",
    moreOptions:"Mais op&#231;&#245;es",
    lessOptions:"Menos op&#231;&#245;es",
    help:"Ajuda",
    helpHref:"http://sobre.arquivo.pt/ajuda",
    newSearch:"Nova pesquisa",
    at:"&#224;s",
    shareMessage:"Arquivo.pt",
    language:"pt",
    otherDates:"Tabela de vers&#245;es",
    emailMessage:"P&#225gina Interessante Do Passado &body=",
    noResultsFound:"N&#227;o foram encontrados resultados para a sua pesquisa:",
    suggestions:"Sugerimos que:",
    checkSpelling:"Verifique o URL",
    differentKeywords:"Tente utilizar outras palavras-chave.",
    generalWords:"Tente palavras mais gerais.", 
    internetArchive:"Pesquise no",
    suggestSiteArchived:"a p&#225gina para que seja arquivada.",
    suggestUrl:"http://sobre.arquivo.pt/colaboracoes/sugerir-um-sitio?endereco-a-sugerir=",
    suggest:"Sugira", 
    mementoFind:"Pesquise outros arquivos web",
    embargo:"Embargo",
    embargoUrl:"http://sobre.arquivo.pt/ajuda/acesso-a-conteudos-arquivados#section-6",
    notArchived:"N&#227;o Arquivado",
    otherLanguage: "EN"  ,
    preservedByArquivo: " - preservada pelo Arquivo.pt"   ,
    faceTitle: "Partilhar no Facebook",
    twitterTitle: "Partilhar no Twitter",
    mailTitle: "Partilhar por Email",
    screenTitle: "Guardar como Imagem",
    printTitle: "Imprimir a P&#225gina" ,
    changeLanguageTitle: "Change to English language" ,
    versionsStoredTable:"Tabela de Vers&#245es", 
    suggestArchive: "Sugira o Arquivo desta página",
    ups: "Ups...",
    theWebsite: "O Website",
    notArchivedYet: "ainda não foi arquivado.",
    searchTitle: "Pesquise no Arquivo",
    otherArchives: "Pesquisar noutros arquivos",
    table: "Tabela",
    completePage: "Completar a P&#225gina",
    downloadTitle: "Guardar como Imagem",
    downloadPopup: "Guardar p&#225gina arquivada como imagem?",
    downloadMessage: "Guardar",
    downloadCancel: "Cancelar",
    title500: "Ooops! Ocorreu um erro",
    subtitle500: "Pedimos desculpa por este imprevisto.",
    suggestionsTitle500: "Poder&#225:",
    suggestionsFeedback500: "Avise-nos do problema",
    goHome500: "Volte &#224 p&#225gina inicial",
    homePagetitle: "Ir para a p&#225gina principal", 
    contact: "contacto?set_language=pt",
    iongrid: "Icone tabela de vers&#245es" ,
    reconstructImg: "Icone completar a p&#225gina" ,
    screenshotIcon: "Icone guardar p&#225gina como imagem" ,
    printIcon: "Icone imprimir a p&#225gina" ,
    facebookIcon: "Icone partilhar no Facebook",
    twitterIcon: "Icone partilhar no Twitter",
    emailIcon: "Icone partilhar por email",
    minimizeMaximizeTitle: "Minimizar ou maximizar barra de ferramentas",
    minimizeMaximizeIcon: "Icone minimizar ou maximizar barra de ferramentas",
    allVersions: "Listar vers&#245;es",
    facebook: "Facebook",
    twitter: "Twitter",
    email: "Email",
    otherLanguageExtended: "English",
    complete: "Completar",
    saveImage: "Guardar",
    print: "Imprimir",
    share: "Partilhar",
    tools: "Ferramentas",
    printModalTitle: "Imprimir esta p&aacute;gina?",
    cancel: "Cancelar",
    saveAsImage: "Guardar esta p&aacute;gina como imagem?",
    completeThisPage: "Completar esta p&aacute;gina?",
    leavingArquivo: "Vai sa&iacute;r do Arquivo.pt",
    toBeCompleted: "Esta p&aacute;gina porder&aacute; ser completada com informa&ccedil;&atilde;o em falta.",
    helpHref:"http://sobre.arquivo.pt/pt/ajuda/"      

};
