collections:
  live: $live

  save:
    archive_paths: archive
    index_paths: indexes

framed_replay: false
redirect_to_exact: true
enable_auto_fetch: true
autoindex: 30

debug: True

recorder:
   source_coll: live
   rollover_size: 100000000
   rollover_idle_secs: 600
   filename_template: savepage-{timestamp}-{hostname}-{random}.warc.gz
   source_filter: live