name: Build and Push Docker Images
description: This workflow builds and pushes Docker images for pywb instances of the Arquivo.pt

on:
  push:
    branches:
      - main
      - master
    tags:
      - '*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [framed, patching, save, unframed]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract short SHA
        id: vars
        run: echo "SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.service}}/.
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/pywb-arquivo-${{ matrix.service}}:${{ github.ref_name }}
            ${{ secrets.DOCKERHUB_USERNAME }}/pywb-arquivo-${{ matrix.service}}:${{ env.SHORT_SHA }}

      - name: Logout from Docker Hub
        run: docker logout
